/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserProfile = IDL.Record({
  'network' : IDL.Text,
  'walletAddress' : IDL.Text,
});
export const MarketData = IDL.Record({
  'token' : IDL.Text,
  'change24h' : IDL.Float64,
  'price' : IDL.Float64,
});
export const TokenBalance = IDL.Record({
  'token' : IDL.Text,
  'balance' : IDL.Float64,
  'price' : IDL.Float64,
});
export const StakingPool = IDL.Record({
  'apy' : IDL.Float64,
  'totalStaked' : IDL.Float64,
  'poolName' : IDL.Text,
  'userStaked' : IDL.Float64,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'token' : IDL.Text,
  'timestamp' : Time,
  'txType' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getMarketData' : IDL.Func([], [IDL.Vec(MarketData)], ['query']),
  'getPortfolio' : IDL.Func([], [IDL.Vec(TokenBalance)], ['query']),
  'getStakingPools' : IDL.Func([], [IDL.Vec(StakingPool)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserProfile = IDL.Record({
    'network' : IDL.Text,
    'walletAddress' : IDL.Text,
  });
  const MarketData = IDL.Record({
    'token' : IDL.Text,
    'change24h' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const TokenBalance = IDL.Record({
    'token' : IDL.Text,
    'balance' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const StakingPool = IDL.Record({
    'apy' : IDL.Float64,
    'totalStaked' : IDL.Float64,
    'poolName' : IDL.Text,
    'userStaked' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'token' : IDL.Text,
    'timestamp' : Time,
    'txType' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getMarketData' : IDL.Func([], [IDL.Vec(MarketData)], ['query']),
    'getPortfolio' : IDL.Func([], [IDL.Vec(TokenBalance)], ['query']),
    'getStakingPools' : IDL.Func([], [IDL.Vec(StakingPool)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };