/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MarketData {
  'token' : string,
  'change24h' : number,
  'price' : number,
}
export interface StakingPool {
  'apy' : number,
  'totalStaked' : number,
  'poolName' : string,
  'userStaked' : number,
}
export type Time = bigint;
export interface TokenBalance {
  'token' : string,
  'balance' : number,
  'price' : number,
}
export interface Transaction {
  'token' : string,
  'timestamp' : Time,
  'txType' : string,
  'amount' : number,
}
export interface UserProfile { 'network' : string, 'walletAddress' : string }
export interface _SERVICE {
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getMarketData' : ActorMethod<[], Array<MarketData>>,
  'getPortfolio' : ActorMethod<[], Array<TokenBalance>>,
  'getStakingPools' : ActorMethod<[], Array<StakingPool>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'setUserProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];